giveConsistencyEVTYPE <- function(storm){

    storm[,c(8)] <- sapply(storm[,c(8)],as.character) 
    
    #I give some consistency to EVTYPE
    storm[grep("ASTRONOMICAL LOW TIDE", storm$EVTYPE),]$EVTYPE <- c("Astronomical Low Tide")
    storm[grep("AVALANCHE", storm$EVTYPE),]$EVTYPE <- c("Avalanche")
    storm[grep("BLIZZARD", storm$EVTYPE),]$EVTYPE <- c("Blizzard")
    storm[grep("COASTAL FLOODING|ASTRONOMICAL HIGH|COASTAL FLOOD", storm$EVTYPE),]$EVTYPE <- c("Coastal Flood")
    storm[grep("COLD/WIND CHILL", storm$EVTYPE),]$EVTYPE <- c("Cold/Wind Chill")
    storm[grep("LANDSPOUT|LANDSLIDE|MUDSLIDE|MUD SLIDE", storm$EVTYPE),]$EVTYPE <- c("Debris Flow")
    storm[grep("^FOG|DENSE FOG", storm$EVTYPE),]$EVTYPE <- c("Dense Fog")
    storm[grep("DENSE SMOKE", storm$EVTYPE),]$EVTYPE <- c("Dense Smoke")
    storm[grep("DRY MICROBURST|DROUGHT", storm$EVTYPE),]$EVTYPE <- c("Drought")
    storm[grep("DUST DEVIL", storm$EVTYPE),]$EVTYPE <- c("Dust Devil")
    storm[grep("DUST STORM|BLOWING DUST", storm$EVTYPE),]$EVTYPE <- c("Dust Storm")
    storm[grep("EXCESSIVE HEAT|WARM WEATHER|HEAT", storm$EVTYPE),]$EVTYPE <- c("Excessive Heat")
    storm[grep("EXTREME COLD|EXTREME WINDCHILL|COLD|LATE SEASON SNOW|COLD WEATHER|EXTREME COLD/WIND CHILL", storm$EVTYPE),]$EVTYPE <- c("Extreme Cold/Wind Chill")
    storm[grep("FLASH FLOOD|FLOOD/FLASH/FLOOD|FLASH FLOOD/FLOOD|DAM BREAK| FLASH FLOOD", storm$EVTYPE),]$EVTYPE <- c("Flash Flood")
    storm[grep("URBAN/SML STREAM FLD|^FLOOD", storm$EVTYPE),]$EVTYPE <- c("Flood")
    storm[grep("FREEZE|ICY ROADS|LIGHT SNOW|FREEZING RAIN|LIGHT FREEZING RAIN|ICE ROADS|ICE ON ROAD|FROST/FREEZE", storm$EVTYPE),]$EVTYPE <- c("Frost/Freeze")
    storm[grep("FUNNEL CLOUD", storm$EVTYPE),]$EVTYPE <- c("Funnel Cloud")
    storm[grep("FREEZING FOG", storm$EVTYPE),]$EVTYPE <- c("Freezing Fog")
    storm[grep("HAIL|SMALL HAIL|GUSTY WIND/HAIL", storm$EVTYPE),]$EVTYPE <- c("Hail")
    storm[grep("UNSEASONABLY WARM|RECORD HEAT", storm$EVTYPE),]$EVTYPE <- c("Heat")
    storm[grep("HEAVY RAIN|UNSEASONAL RAIN|MIXED PRECIPITATION|RAIN", storm$EVTYPE),]$EVTYPE <- c("Heavy Rain")
    storm[grep("HEAVY SNOW|^SNOW|EXCESSIVE SNOW|FALLING SNOW/ICE|SNOW SQUALLS", storm$EVTYPE),]$EVTYPE <- c("Heavy Snow")
    storm[grep("HEAVY SURF|HIGH SURF|HEAVY SEAS|ROUGH SEAS|HIGH WATER|ROGUE WAVE|   HIGH SURF ADVISORY|HAZARDOUS SURF|HEAVY SURF/HIGH SURF", storm$EVTYPE),]$EVTYPE <- c("High Surf")
    storm[grep("HIGH WIND|GUSTY WIND|^WIND|NON-SEVERE WIND DAMAGE", storm$EVTYPE),]$EVTYPE <- c("High Wind")
    storm[grep("HURRICANE|HURRICANE/TYPHOON", storm$EVTYPE),]$EVTYPE <- c("Hurricane (Typhoon)")
    storm[grep("ICE STORM", storm$EVTYPE),]$EVTYPE <- c("Ice Storm")
    storm[grep("LAKE EFFECT SNOW|LAKE-EFFECT SNOW", storm$EVTYPE),]$EVTYPE <- c("Lake-Effect Snow")
    storm[grep("LAKESHORE FLOOD", storm$EVTYPE),]$EVTYPE <- c("Lakeshore Flood")
    storm[grep("LIGHTNING", storm$EVTYPE),]$EVTYPE <- c("Lightning")
    storm[grep("DROWNING|MARINE HAIL", storm$EVTYPE),]$EVTYPE <- c("Marine Hail")
    storm[grep("WIND AND WAVE|HIGH SEAS|MARINE HIGH WIND", storm$EVTYPE),]$EVTYPE <- c("Marine High Wind")
    storm[grep("MARINE STRONG WIND", storm$EVTYPE),]$EVTYPE <- c("Marine Strong Wind")
    storm[grep("MARINE TSTM WIND|MARINE THUNDERSTORM WIND", storm$EVTYPE),]$EVTYPE <- c("Marine Thunderstorm Wind")
    storm[grep("RIP CURRENTS|RIP CURRENT", storm$EVTYPE),]$EVTYPE <- c("Rip Current")
    storm[grep("SEICHE", storm$EVTYPE),]$EVTYPE <- c("Seiche")
    storm[grep("STORM SURGE|STORM SURGE/TIDE", storm$EVTYPE),]$EVTYPE <- c("Storm Surge/Tide")
    storm[grep("STRONG WINDS|GUSTY WINDS|STRONG WIND|NON-TSTM WIND|NON TSTM WIND|WHIRLWIND", storm$EVTYPE),]$EVTYPE <- c("Strong Wind")
    storm[grep("TSTM WIND/HAIL|TSTM WIND|TSTM WIND (G45)|TSTM WIND (G40)| TSTM WIND|TSTM WIND G45|THUNDERSTORM WIND (G40)|THUNDERSTORM|THUNDERSTORM WIND", storm$EVTYPE),]$EVTYPE <- c("Thunderstorm Wind")
    storm[grep("TORNADO", storm$EVTYPE),]$EVTYPE <- c("Tornado")
    storm[grep("TROPICAL DEPRESSION", storm$EVTYPE),]$EVTYPE <- c("Tropical Depression")
    storm[grep("TROPICAL STORM", storm$EVTYPE),]$EVTYPE <- c("Tropical Storm")
    storm[grep("TSUNAMI", storm$EVTYPE),]$EVTYPE <- c("Tsunami")
    storm[grep("VOLCANIC ASH", storm$EVTYPE),]$EVTYPE <- c("Volcanic Ash")
    storm[grep("WATERSPOUT", storm$EVTYPE),]$EVTYPE <- c("Waterspout")
    storm[grep("WILD/FOREST FIRE|BRUSH FIRE|WILDFIRE", storm$EVTYPE),]$EVTYPE <- c("Wildfire")
    storm[grep("WINTER STORM", storm$EVTYPE),]$EVTYPE <- c("Winter Storm")
    storm[grep("WINTRY MIX|WINTER WEATHER MIX|WINTER WEATHER/MIX|WINTER WEATHER", storm$EVTYPE),]$EVTYPE <- c("Winter Weather")
    storm[grep("OTHER", storm$EVTYPE),]$EVTYPE <- c("Other")
    
    storm[,c(8)] <- sapply(storm[,c(8)],as.factor) 
    
    return (storm)
}